### ISSUE TITLE
Generalize button tag to use mwc-button

### ISSUE THREAD

**Issue by leemyunggyu** [things-factory/things-factory#100]
Generalize button tag to use `mwc-button`

There are some mixed types of button tags.

Some are using `<button></button>`, some are using `<input type="submit" />` and `<mwc-button></mwc-button>`

it's recommended to use `<mwc-button></mwc-button>` to generalize mixed use cases.
By doing so we can shorten source code and get efficient way to manage every buttons.

**Comment by hoppaang** [comment]
ref. image
![image](https://user-images.githubusercontent.com/1257178/102030719-27454680-3df7-11eb-84ff-17c0f3beb100.png)

_code_
**button - high emphasis "raised"**
`<mwc-button raised label=“Save”></mwc-button>`

**danger button - high emphasis "raised danger"**
`css : [danger] {
          —mdc-theme-primary : var(—mdc-danger-button-primary-color);
        }
html : <mwc-button raised danger label=“Delete”></mwc-button>`

**button - medium emphasis "outlined"**
`<mwc-button outlined label=“Save”></mwc-button>`

**danger button - medium emphasis "outlined danger"**
`css : [danger] {
          —mdc-theme-primary : var(—mdc-danger-button-primary-color);
          —mdc-button-outline-color : var(—mdc-danger-button-outline-color);
        }
html : <mwc-button outlined danger label=“Delete”></mwc-button>`

**Comment by heartyoh** [comment]
:thumbsup:
