### ISSUE TITLE
Improve domain selection page

### ISSUE THREAD

**Issue by leemyunggyu** [things-factory/things-factory#101]
Improve domain selection page

**Comment by hoppaang** [comment]
ref. image
![image](https://user-images.githubusercontent.com/1257178/102030651-ec431300-3df6-11eb-8c00-808a6d4693cf.png)

**Comment by heartyoh** [comment]
![Screen Shot 2020-12-15 at 10 29 53 PM](https://user-images.githubusercontent.com/1239480/102221163-21e61a00-3f25-11eb-8aee-276dfad76366.png)
- '>' 가 위로 약간 치우침
- 도메인의 디스크립션 정도는 추가되면 좋겠군요.

**Comment by hoppaang** [comment]
![image](https://user-images.githubusercontent.com/1257178/102282240-a3649900-3f73-11eb-80bb-99940a401bcf.png)

**Comment by heartyoh** [comment]
👍
