### ISSUE TITLE
[typo] priviledge => privilege

### ISSUE THREAD

**Issue by heartyoh** [things-factory/things-factory#123]

**Comment by leemyunggyu** [comment]
# How to adjust changes to existing database

If you need to run application with existing database after pulling down latest source which has this changes.
You should change your current schema of database by manual.

### Following steps should be done before you launch the application.

1. Change current name of tables to changed one.
> Affected tables are `priviledges` & `roles_priviledges`,  you need to change `priviledges` => `privileges` & `roles_priviledges` => `roles_privileges`

2. Remove `Constraints` and `Foreign keys`
> Please remove every `constraints` and `foreign keys` setting in each of tables (privileges, roles_privileges)

3. Launch application
> It will generate removed constraints and foreign keys automatically.
