### ISSUE TITLE
[operato-hub] make it easy to classify users by user type.

### ISSUE THREAD

**Issue by heartyoh** [things-factory/things-factory#99]
- 유저 타입은 다음 3가지가 있습니다. application, appliance and human user.
- 유저 메뉴에서 사용자 타입별로 탭으로 구분하도록 합니다.

**Comment by hoppaang** [comment]
가연씨가 개발 했고, 저는 곁다리로 스타일 이상한 부분만 교정 해서 올렸습니다

**Comment by heartyoh** [comment]
잘하셨습니다.
